// <auto-generated />
using ASP.NET_CRUD_example_1._3_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASP.NET_CRUD_example_1._3_DAL.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    partial class PostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("AlumnoAsignatura", b =>
                {
                    b.Property<int>("ListaAlumnosId")
                        .HasColumnType("integer");

                    b.Property<int>("ListaAsignaturasId")
                        .HasColumnType("integer");

                    b.HasKey("ListaAlumnosId", "ListaAsignaturasId");

                    b.HasIndex("ListaAsignaturasId");

                    b.ToTable("AlumnoAsignatura");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_1._3_DAL.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AlumnoApellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlumnoEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlumnoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ASP.NET_CRUD_example_1._3_DAL.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AsignaturaNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("AlumnoAsignatura", b =>
                {
                    b.HasOne("ASP.NET_CRUD_example_1._3_DAL.Alumno", null)
                        .WithMany()
                        .HasForeignKey("ListaAlumnosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_CRUD_example_1._3_DAL.Asignatura", null)
                        .WithMany()
                        .HasForeignKey("ListaAsignaturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
